### ISSUE TITLE
Any plans to develop this further?

### ISSUE THREAD

**Issue by kha-white** [bluaxees/Poricom#1]
Hi,
I just found out about this project, pretty cool to see it making a good use of manga-ocr! I think this could be a good option for people who would like to use manga-ocr, but would prefer a ready-to-use exe instead of having to deal with setting up Python, Sharex etc. 

Do you have any plans for further development? There are some missing features, which in my opinion could make it more accessible for users (in order of importance):
- zooming in and out
- showing two pages at once
- moving around with a mouse while zoomed in (like a typical "hand tool")
- support for popular formats like cbz and cbr
- moving to the next page by scrolling down

**Comment by bluaxees** [comment]
Hello, I am planning to add the functionalities of a standard image viewer applications i.e. zooming and the "hand tool" that you mentioned, among other QOL features. As for your other suggestions, I will consider them (I also think that navigating to the next image is quite clunky). But don't expect immediate updates as I will be busy for some time.

**Comment by foss1234** [comment]
@bluaxees please add dark mode too

**Comment by bluaxees** [comment]
Hello, I have added the following features in the [latest release](https://github.com/bluaxees/Poricom/releases/latest/):
- zooming in and out
- panning an image
- support for cbz and cbr formats
- access to dark mode

As for the unimplemented features that were requested, I might revisit them in the future.
