### ISSUE TITLE
running "pyinstaller main.spec" in terminal gives back an error

### ISSUE THREAD

**Issue by JakeJayB** [bluaxees/Poricom#10]
Hello, 

When I was trying to build this app using pyinstaller as you stated, I was given back a "pkg_resources.DistributionNotFound:" error. Am I missing something? See error below

![f7ffe69a1cf25de0e8cbbf535b38824a](https://user-images.githubusercontent.com/84160208/185717675-e886c100-2fb6-4673-b328-8e06c46417d4.png)

**Comment by bluaxees** [comment]
I forgot to include `toml` in the requirements. Running `pip install toml` should fix your issue.
