### ISSUE TITLE
Why doesn't the model change?

### ISSUE THREAD

**Issue by OneDefauter** [bluaxees/Poricom#11]
[Here a video showing.](https://drive.google.com/file/d/1zBrWDZu7I17qA0pJreOC1HcqHlD-13rQ/view?usp=sharing)
https://drive.google.com/file/d/1zBrWDZu7I17qA0pJreOC1HcqHlD-13rQ/view?usp=sharing

did i do wrong?

**Comment by bluaxees** [comment]
Hello, can you please upload a shorter video that summarizes your problem? Also, if you can, please explain what you're trying to achieve since I don't see any problem on your demo video

**Comment by OneDefauter** [comment]
https://user-images.githubusercontent.com/27703239/193419024-a2f68fd5-0ac9-4b50-b722-95f6218c918d.mp4

The problem is: even if you change the language model and set it to horizontal it doesn't recognize the English text like the Japanese language model.

**Comment by bluaxees** [comment]
Based on README, you can:
> Change language and/or orientation (limited to the Tesseract API).

This means that the language and orientation settings only works when using the Tesseract model. On your video, you are using the MangaOCR model which works best when detecting vertical Japanese text though it can detect English text to some degree.
