### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by DominiqueSite** [bluaxees/Poricom#12]
Hey, I had problems installing Poricom on Fedora 36.
To make the installation easier for Linux users and to get additional exposure, please consider packaging Poricom as a [Flatpak](https://www.flatpak.org/) and publishing it e.g. via [Flathub](https://flathub.org/)!

**Comment by bluaxees** [comment]
You can't "install" this app on a non-Windows system. Right now, the only way to get it running on Linux is to clone this repo and run the app using `python main.py`.
