### ISSUE TITLE
Model download error

### ISSUE THREAD

**Issue by lhj5426** [bluaxees/Poricom#15]
![image](https://user-images.githubusercontent.com/30548000/203996105-2124c451-149f-4db6-883b-52e155af31dd.png)
Model download error
Obviously there is a network, but it keeps saying that there is no network
Is there an offline model download?

**Comment by bluaxees** [comment]
To check for internet connection, Poricom pings Google's DNS server. Can you try pinging 8.8.8.8 and see if it's not blocked?

Also, what OS are you using?

**Comment by lhj5426** [comment]
> To check for internet connection, Poricom pings Google's DNS server. Can you try pinging 8.8.8.8 and see if it's not blocked?
> 
> 
> 
> Also, what OS are you using? 

win 21H2 
Can I provide a good job cache file in your computer?

**Comment by bluaxees** [comment]
I don't know what you mean by good job cache file.

You just need to test if 8.8.8.8 is reachable. If it's not, find a way to unblock it.

**Comment by lhj5426** [comment]
Send me the MangaOcr cache file you have downloaded

If I import it to the corresponding folder path, it can be used, right?

**Comment by lhj5426** [comment]
It's convenient for me

 No need to download it, it has nothing to do with 8.8.8.8

**Comment by lhj5426** [comment]
MangaOcr offline cache files

give me

**Comment by lhj5426** [comment]
can you understand

**Comment by lhj5426** [comment]
serve cached files
People with poor internet can also use it
There is no need to download the cache file that I don’t know if it can be downloaded from the Internet


This is convenient for everyone

**Comment by lhj5426** [comment]
Put the downloaded ones in your computer

MangaOcr cache files are packaged into zip

**Comment by lhj5426** [comment]
because my mother tongue is not english

I communicate with you through Google Translate

There may be differences in the sentence, which is not easy to understand?

**Comment by bluaxees** [comment]
Even if I send you the cached MangaOcr model, it still wouldn't work since you didn't pass the internet connectivity test. 

Also, HuggingFace/manga-ocr redownloads the model even if it already exist in your cache. This means the app would not work if you download the files and place it on your cache folder. See my answer on #9 regarding this issue.

If you still want to do this, you may download the files in this [link](https://huggingface.co/kha-white/manga-ocr-base/tree/main).

**Comment by lhj5426** [comment]
Let me try this first, thank you

**Comment by lhj5426** [comment]
i give up no

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/204127939-b080c4a3-44f2-4bd5-af9f-ade90bc915d4.png)
Isn't this thing offline?
Why do you still use the Internet?
Can't the local server and local network be enough?

**Comment by bluaxees** [comment]
You need internet connection to download the files. After loading the model, internet connection shouldn't matter

**Comment by yangshu88** [comment]
I tested that ping 8.8.8.8 can connect, but I still cannot download the MangaOCR model. The same prompt as in the picture

**Comment by bluaxees** [comment]
This should be fixed in [v0.4.0](https://github.com/bluaxees/Poricom/releases/tag/v0.4.0)
