### ISSUE TITLE
None of the OCR model working

### ISSUE THREAD

**Issue by Tobrux** [bluaxees/Poricom#17]
For some reson both OCR models give me a blank result if I try any text, and I've let the program download the manga-ocr model with no network issues. I've also tried with bigger text and higher resolution images but it still wont work.
An example here
![ocr](https://user-images.githubusercontent.com/97679212/207984461-dd8b6071-259e-4338-a0cb-6327215bfe13.PNG)

**Comment by bluaxees** [comment]
What zip file are you using? Also please tell me your OS version and what GPU you have.

**Comment by Tobrux** [comment]
Windows 10, GeForce 920MX. I tried the normal zip and the CPU zip. The normal zip (used above) has this problems, the CPU one doesn't work either, and if I let it download manga-ocr it crashes

**Comment by bluaxees** [comment]
Have you tried if the tesseract models work? To use it, either don't load or unload the manga-ocr model. 

Also, I'm not sure if you're already doing this since you only uploaded an image, but you need to hold the left mouse button and wait for the model to predict the text to see the result

**Comment by Tobrux** [comment]
I tried waiting for both tesseract and manga-ocr a good 15 minutes but nothing worked. I tryed on the CPU version with tesseract (manga-ocr doesn't get loaded, it just crashes) and even after clicking the program showed no CPU usage. And yes I know I have to release after highlighting the text

**Comment by bluaxees** [comment]
> waiting for both tesseract and manga-ocr a good 15 minutes
> I have to release after highlighting the text

I think you misunderstood. After highlighting the text, you wait for a few seconds (2 should be enough) until the prediction is shown. That's when you release the left mouse button. No need to wait for that long

**Comment by Tobrux** [comment]
Welp it works, now I fell dumb. Just to not waste this issue, the CPU version crashes when iI try to load manga-ocr, any idea what it could be?

**Comment by bluaxees** [comment]
Tbf a few users had the same problem before, I think I need to change the default behavior.

The CPU version was my attempt to support non-NVIDIA GPUs. It might be crashing because it uses the CPU version of `torch`
