### ISSUE TITLE
Preview text size and customizable shortcuts.

### ISSUE THREAD

**Issue by dekinaidesu** [bluaxees/Poricom#2]
Hey, I like your program. 

I'd like to suggest features that you can add in the future. 

1) Adjustable preview text size. The preview text on the right corner should be adjustable. especially on big curved screens, it's hard to read. 

2) customisable capture images outside the application shortcuts.
instead of alt+q, add the choice for more customisable controls.

**Comment by bluaxees** [comment]
Hello, I have added the following features are added in the latest release:
- Change font style and font size of preview text
- Customize shortcut for external capture

You may see the other changes in [this link](https://github.com/bluaxees/Poricom/blob/38ce215dd4ef49985860e06025d9d4d66a58679d/CHANGELOG.md).
