### ISSUE TITLE
Suggestion: Scroll to change pages and fit to page option

### ISSUE THREAD

**Issue by FirionHope** [bluaxees/Poricom#3]
Just discovered this and its exactly what I was looking for, seems amazing! Shared it with friends who seem interested too.

Anyway as for the suggestion the current thing I use to read manga (CDisplayEx) has both a mode to fit the size of the image to the screen size so you don't have to scroll and by default you can change pages by using scroll wheel up or down. This makes reading feel much nicer as one scroll wheel down or up will change the page guaranteed, and you already need your hand on the mouse to select text with Poricom anyway. Example image: https://i.imgur.com/E5VdDYl.png 

Implementing this in Poricom would greatly improve it's QOL imo, scrolling should simply move to the next/previous image in the "queue" on the left.

**Comment by bluaxees** [comment]
Hello, I have added the following features in the latest release:
- Image navigation using the scroll wheel
- Option to change image scaling

You may see the other changes in [this link](https://github.com/bluaxees/Poricom/blob/38ce215dd4ef49985860e06025d9d4d66a58679d/CHANGELOG.md).
