### ISSUE TITLE
Reporting a few bugs.

### ISSUE THREAD

**Issue by majortomomeganebula** [bluaxees/Poricom#4]
The program looked promising, so I played around with it. There were a few bugs. 

1. Inconsistency in switching themes: You can't save your preferences if you switch between dark and light themes. In other words, if I set the theme to dark, close the program, and then reopen it, it turns back to light. 

2. By starting the program offline (without being connected to the internet) and choosing yes when it asks you to download the MangaOCR model. It just shuts down, without showing any prompt messages such as (you can't download it because you're connected to the internet. etc) 
 
3. In addition, it keeps asking you to download the MangaOCR model every time when switching the "detection model", even if you have it already installed.

**Comment by bluaxees** [comment]
Hello, thank you for reporting these bugs. 

Regarding point 3, that is intended. Even though you have the MangaOCR model downloaded, it will still take some time to load it, hence the prompt.
