### ISSUE TITLE
Option to minimize explorer/sidebar

### ISSUE THREAD

**Issue by djter103vforvendetta** [bluaxees/Poricom#8]
Hey. Great App! 
Please consider adding the option to hide Manga Directory Tab on the right. 

![Poricom_BbZAsZfNn2](https://user-images.githubusercontent.com/104341134/165024991-6309defb-2122-4e60-b4e4-349bf9ddc401.jpg)

**Comment by bluaxees** [comment]
This request was mentioned in #6 and will be included in the next major release
